import {
  EquipementStatut,
  MaintenanceType,
  Periodicite,
  Role,
} from "@prisma/client";

export const presentationServices = [
  "Surete aeroportuaire",
  "Traitement bagages",
  "Electricite balisage",
  "Energie et automatismes",
  "Systemes d'information",
  "Telecommunications",
  "Infrastructures terminal",
];

export const presentationFamilies = [
  "Scanner Rayon X",
  "Detecteur de traces",
  "Portique detecteur de metaux",
  "Convoyage bagages",
  "Balisage lumineux",
  "Alimentation secourue",
  "Teleaffichage",
  "Equipement reseau",
  "Radiocommunication",
  "Controle d'acces",
  "Securite incendie",
  "Climatisation",
];

export const presentationZones = [
  "PIF Depart - Zone A",
  "PIF Depart - Zone B",
  "Tri bagages depart",
  "Livraison bagages arrivee",
  "Piste 09/27",
  "Local technique balisage",
  "Salle serveurs",
  "Hall public depart",
  "Salle embarquement",
  "Poste de commandement",
  "Locaux energie",
  "Zone fret",
];

export const presentationUsers = [
  {
    email: "presentation.admin@aeromaint.local",
    nom: "Bennani",
    prenom: "Salma",
    role: Role.ADMIN,
    service: "Systemes d'information",
  },
  {
    email: "presentation.superviseur@aeromaint.local",
    nom: "El Amrani",
    prenom: "Karim",
    role: Role.SUPERVISEUR,
    service: "Energie et automatismes",
  },
  {
    email: "youssef.benali@presentation.aeromaint.local",
    nom: "Benali",
    prenom: "Youssef",
    role: Role.TECHNICIEN,
    service: "Surete aeroportuaire",
  },
  {
    email: "nora.alaoui@presentation.aeromaint.local",
    nom: "Alaoui",
    prenom: "Nora",
    role: Role.TECHNICIEN,
    service: "Traitement bagages",
  },
  {
    email: "hamza.idrissi@presentation.aeromaint.local",
    nom: "Idrissi",
    prenom: "Hamza",
    role: Role.TECHNICIEN,
    service: "Electricite balisage",
  },
  {
    email: "imane.tazi@presentation.aeromaint.local",
    nom: "Tazi",
    prenom: "Imane",
    role: Role.TECHNICIEN,
    service: "Systemes d'information",
  },
  {
    email: "mehdi.chraibi@presentation.aeromaint.local",
    nom: "Chraibi",
    prenom: "Mehdi",
    role: Role.TECHNICIEN,
    service: "Telecommunications",
  },
  {
    email: "sara.ouazzani@presentation.aeromaint.local",
    nom: "Ouazzani",
    prenom: "Sara",
    role: Role.TECHNICIEN,
    service: "Infrastructures terminal",
  },
];

type PresentationEquipment = {
  code: string;
  nom: string;
  marque: string;
  numeroSerie: string;
  service: string;
  famille: string;
  zone: string;
  statut: EquipementStatut;
  prixAcquisition: number;
  modeIntegre: boolean;
  qrAppose: boolean;
  remarques: string;
  miseEnServiceDaysAgo: number;
  remplacementDaysAhead: number;
  dateArretDaysAgo?: number;
  planning?: {
    type: MaintenanceType;
    periodicite: Periodicite;
    technicienEmail: string;
    eviterWeekend?: boolean;
    nuit?: boolean;
  };
};

export const presentationEquipments: PresentationEquipment[] = [
  {
    code: "ESU-SUR-RX-01",
    nom: "Scanner RX bagages cabine PIF A1",
    marque: "Smiths Detection HI-SCAN 6040i",
    numeroSerie: "SD-6040I-22-1845",
    service: "Surete aeroportuaire",
    famille: "Scanner Rayon X",
    zone: "PIF Depart - Zone A",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 487000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Poste principal du filtre surete. Controle quotidien de la qualite image.",
    miseEnServiceDaysAgo: 790,
    remplacementDaysAhead: 1460,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-SUR-RX-02",
    nom: "Scanner RX bagages cabine PIF A2",
    marque: "Smiths Detection HI-SCAN 6040i",
    numeroSerie: "SD-6040I-22-1851",
    service: "Surete aeroportuaire",
    famille: "Scanner Rayon X",
    zone: "PIF Depart - Zone A",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 487000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Poste secondaire utilise lors des pointes de trafic.",
    miseEnServiceDaysAgo: 788,
    remplacementDaysAhead: 1460,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-SUR-RX-03",
    nom: "Scanner RX bagages cabine PIF B1",
    marque: "Rapiscan 620XR",
    numeroSerie: "RP-620XR-23-0412",
    service: "Surete aeroportuaire",
    famille: "Scanner Rayon X",
    zone: "PIF Depart - Zone B",
    statut: EquipementStatut.EN_PANNE,
    prixAcquisition: 432000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Panne intermittente du convoyeur d'entree. Diagnostic moteur en cours.",
    miseEnServiceDaysAgo: 620,
    remplacementDaysAhead: 1640,
    dateArretDaysAgo: 3,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-SUR-ETD-01",
    nom: "Detecteur de traces ETD PIF A",
    marque: "Smiths Detection IONSCAN 600",
    numeroSerie: "ION600-21-0918",
    service: "Surete aeroportuaire",
    famille: "Detecteur de traces",
    zone: "PIF Depart - Zone A",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 268000,
    modeIntegre: false,
    qrAppose: true,
    remarques: "Verification hebdomadaire avec consommable de reference.",
    miseEnServiceDaysAgo: 970,
    remplacementDaysAhead: 1180,
    planning: {
      type: MaintenanceType.ETALONNAGE,
      periodicite: Periodicite.HEBDOMADAIRE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-SUR-WTMD-01",
    nom: "Portique detecteur de metaux PIF A",
    marque: "CEIA PMD2 Plus",
    numeroSerie: "CEIA-PMD2-20-3321",
    service: "Surete aeroportuaire",
    famille: "Portique detecteur de metaux",
    zone: "PIF Depart - Zone A",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 94000,
    modeIntegre: false,
    qrAppose: true,
    remarques: "Essai des zones de detection et controle des alarmes sonores.",
    miseEnServiceDaysAgo: 1230,
    remplacementDaysAhead: 950,
    planning: {
      type: MaintenanceType.CONTROLES_REGLEMENTAIRES,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-BAG-CV-01",
    nom: "Convoyeur injection banques 01-08",
    marque: "Vanderlande",
    numeroSerie: "VAN-BHS-INJ-01",
    service: "Traitement bagages",
    famille: "Convoyage bagages",
    zone: "Tri bagages depart",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 615000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Ligne critique du tri depart. Graissage et controle tension des bandes.",
    miseEnServiceDaysAgo: 1420,
    remplacementDaysAhead: 1110,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "nora.alaoui@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-BAG-CV-02",
    nom: "Convoyeur injection banques 09-16",
    marque: "Vanderlande",
    numeroSerie: "VAN-BHS-INJ-02",
    service: "Traitement bagages",
    famille: "Convoyage bagages",
    zone: "Tri bagages depart",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 615000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Controle des rouleaux, capteurs photoelectriques et arrets d'urgence.",
    miseEnServiceDaysAgo: 1420,
    remplacementDaysAhead: 1110,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "nora.alaoui@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-BAG-CV-03",
    nom: "Carrousel livraison bagages arrivee",
    marque: "Siemens Logistics",
    numeroSerie: "SIE-CAR-ARR-03",
    service: "Traitement bagages",
    famille: "Convoyage bagages",
    zone: "Livraison bagages arrivee",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 782000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Maintenance planifiee hors plages d'arrivees internationales.",
    miseEnServiceDaysAgo: 1840,
    remplacementDaysAhead: 840,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "nora.alaoui@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-BAL-CCR-01",
    nom: "Regulateur courant constant balisage piste 09",
    marque: "ADB Safegate MCR3",
    numeroSerie: "ADB-MCR3-09-014",
    service: "Electricite balisage",
    famille: "Balisage lumineux",
    zone: "Local technique balisage",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 355000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Intervention de nuit avec coordination tour de controle.",
    miseEnServiceDaysAgo: 2120,
    remplacementDaysAhead: 1060,
    planning: {
      type: MaintenanceType.CONTROLES_REGLEMENTAIRES,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "hamza.idrissi@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-BAL-CCR-02",
    nom: "Regulateur courant constant balisage piste 27",
    marque: "ADB Safegate MCR3",
    numeroSerie: "ADB-MCR3-27-015",
    service: "Electricite balisage",
    famille: "Balisage lumineux",
    zone: "Local technique balisage",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 355000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Mesure d'isolement des boucles avant remise en exploitation.",
    miseEnServiceDaysAgo: 2120,
    remplacementDaysAhead: 1060,
    planning: {
      type: MaintenanceType.CONTROLES_REGLEMENTAIRES,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "hamza.idrissi@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-BAL-PAPI-09",
    nom: "Ensemble PAPI seuil piste 09",
    marque: "ADB Safegate PAPI LED",
    numeroSerie: "ADB-PAPI-09-008",
    service: "Electricite balisage",
    famille: "Balisage lumineux",
    zone: "Piste 09/27",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 224000,
    modeIntegre: false,
    qrAppose: true,
    remarques: "Controle photometrique et verification de l'alignement.",
    miseEnServiceDaysAgo: 860,
    remplacementDaysAhead: 1740,
    planning: {
      type: MaintenanceType.ETALONNAGE,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "hamza.idrissi@presentation.aeromaint.local",
      nuit: true,
    },
  },
  {
    code: "ESU-ENE-GE-01",
    nom: "Groupe electrogene secours terminal",
    marque: "Caterpillar DE550E0",
    numeroSerie: "CAT-DE550-19-7712",
    service: "Energie et automatismes",
    famille: "Alimentation secourue",
    zone: "Locaux energie",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 1285000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Essai en charge mensuel et controle du niveau carburant.",
    miseEnServiceDaysAgo: 2380,
    remplacementDaysAhead: 1280,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "sara.ouazzani@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-ENE-UPS-01",
    nom: "Onduleur salle serveurs 60 kVA",
    marque: "Schneider Electric Galaxy VS",
    numeroSerie: "SE-GVS60-21-1180",
    service: "Energie et automatismes",
    famille: "Alimentation secourue",
    zone: "Salle serveurs",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 318000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Controle batteries, bypass et journal des evenements.",
    miseEnServiceDaysAgo: 1080,
    remplacementDaysAhead: 1460,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "imane.tazi@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-SI-FIDS-01",
    nom: "Ecran FIDS hall depart principal",
    marque: "Samsung QM55B",
    numeroSerie: "SAM-QM55B-23-0188",
    service: "Systemes d'information",
    famille: "Teleaffichage",
    zone: "Hall public depart",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 18500,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Controle affichage, connectivite et redemarrage programme.",
    miseEnServiceDaysAgo: 480,
    remplacementDaysAhead: 1720,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "imane.tazi@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-SI-FIDS-02",
    nom: "Mur FIDS salle embarquement",
    marque: "LG 55VH7J-H",
    numeroSerie: "LG-VH7J-22-0415",
    service: "Systemes d'information",
    famille: "Teleaffichage",
    zone: "Salle embarquement",
    statut: EquipementStatut.EN_PANNE,
    prixAcquisition: 74000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Un module d'affichage hors service. Remplacement planifie.",
    miseEnServiceDaysAgo: 740,
    remplacementDaysAhead: 1310,
    dateArretDaysAgo: 6,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "imane.tazi@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-SI-SW-01",
    nom: "Commutateur coeur de reseau exploitation",
    marque: "Cisco Catalyst 9500",
    numeroSerie: "C9500-ESU-CORE-01",
    service: "Systemes d'information",
    famille: "Equipement reseau",
    zone: "Salle serveurs",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 236000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Verification redondance, alimentations et sauvegarde de configuration.",
    miseEnServiceDaysAgo: 980,
    remplacementDaysAhead: 1580,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "imane.tazi@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-TEL-RAD-01",
    nom: "Relais radio exploitation piste",
    marque: "Motorola SLR 5500",
    numeroSerie: "MOT-SLR5500-20-562",
    service: "Telecommunications",
    famille: "Radiocommunication",
    zone: "Poste de commandement",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 148000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Mesure couverture radio et controle alimentation secourue.",
    miseEnServiceDaysAgo: 1510,
    remplacementDaysAhead: 980,
    planning: {
      type: MaintenanceType.ETALONNAGE,
      periodicite: Periodicite.SEMESTRIELLE,
      technicienEmail: "mehdi.chraibi@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-TEL-PABX-01",
    nom: "Passerelle telephonique operations",
    marque: "Alcatel-Lucent OmniPCX",
    numeroSerie: "ALU-OXE-19-221",
    service: "Telecommunications",
    famille: "Radiocommunication",
    zone: "Poste de commandement",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 214000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Test des lignes prioritaires et export de la configuration.",
    miseEnServiceDaysAgo: 1920,
    remplacementDaysAhead: 760,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "mehdi.chraibi@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-ACC-CTRL-01",
    nom: "Controleur acces portes piste",
    marque: "HID Mercury LP4502",
    numeroSerie: "HID-LP4502-21-090",
    service: "Surete aeroportuaire",
    famille: "Controle d'acces",
    zone: "Poste de commandement",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 86000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Test badges, alarmes de porte et synchronisation serveur.",
    miseEnServiceDaysAgo: 1120,
    remplacementDaysAhead: 1480,
    planning: {
      type: MaintenanceType.CONTROLES_REGLEMENTAIRES,
      periodicite: Periodicite.TRIMESTRIELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
    },
  },
  {
    code: "ESU-INC-SSI-01",
    nom: "Centrale detection incendie terminal",
    marque: "Siemens Cerberus PRO",
    numeroSerie: "SIE-FC2020-18-704",
    service: "Infrastructures terminal",
    famille: "Securite incendie",
    zone: "Poste de commandement",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 395000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Essais par boucle en coordination avec la securite incendie.",
    miseEnServiceDaysAgo: 2520,
    remplacementDaysAhead: 920,
    planning: {
      type: MaintenanceType.CONTROLES_REGLEMENTAIRES,
      periodicite: Periodicite.SEMESTRIELLE,
      technicienEmail: "sara.ouazzani@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-CVC-CTA-01",
    nom: "Centrale traitement air hall depart",
    marque: "Carrier 39HQ",
    numeroSerie: "CAR-39HQ-17-188",
    service: "Infrastructures terminal",
    famille: "Climatisation",
    zone: "Hall public depart",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 542000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Controle filtres, courroies, vibration et temperatures de soufflage.",
    miseEnServiceDaysAgo: 2840,
    remplacementDaysAhead: 780,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "sara.ouazzani@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-CVC-CTA-02",
    nom: "Centrale traitement air salle embarquement",
    marque: "Carrier 39HQ",
    numeroSerie: "CAR-39HQ-17-193",
    service: "Infrastructures terminal",
    famille: "Climatisation",
    zone: "Salle embarquement",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 518000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Maintenance avant la pointe estivale.",
    miseEnServiceDaysAgo: 2840,
    remplacementDaysAhead: 780,
    planning: {
      type: MaintenanceType.ENTRETIEN,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "sara.ouazzani@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-FRT-RX-01",
    nom: "Scanner RX fret hors gabarit",
    marque: "Rapiscan 627DV",
    numeroSerie: "RP-627DV-20-178",
    service: "Surete aeroportuaire",
    famille: "Scanner Rayon X",
    zone: "Zone fret",
    statut: EquipementStatut.EN_SERVICE,
    prixAcquisition: 925000,
    modeIntegre: true,
    qrAppose: true,
    remarques: "Controle qualite image avec mire constructeur.",
    miseEnServiceDaysAgo: 1660,
    remplacementDaysAhead: 1260,
    planning: {
      type: MaintenanceType.ETALONNAGE,
      periodicite: Periodicite.MENSUELLE,
      technicienEmail: "youssef.benali@presentation.aeromaint.local",
      eviterWeekend: true,
    },
  },
  {
    code: "ESU-BAG-CV-OLD",
    nom: "Ancien convoyeur transfert tri 2",
    marque: "Vanderlande",
    numeroSerie: "VAN-BHS-OLD-07",
    service: "Traitement bagages",
    famille: "Convoyage bagages",
    zone: "Tri bagages depart",
    statut: EquipementStatut.HORS_SERVICE,
    prixAcquisition: 286000,
    modeIntegre: false,
    qrAppose: false,
    remarques: "Equipement conserve dans l'historique apres remplacement.",
    miseEnServiceDaysAgo: 4380,
    remplacementDaysAhead: -210,
    dateArretDaysAgo: 180,
  },
];

export const presentationEquipmentCodes = presentationEquipments.map(
  (equipment) => equipment.code,
);

export const presentationUserEmails = presentationUsers.map((user) => user.email);
